### ISSUE TITLE
一个关于字体显示的奇怪问题

### ISSUE THREAD

**Issue by zurica2013** [BigCoke233/matcha#6]
![image](https://user-images.githubusercontent.com/61469060/189038672-ae37eaf7-0728-4a03-ab1a-6ddbc83c8938.png)
如图所示，在站点名称栏，无法正常显示“圃”字，在其他地方或者相近字都可以正常显示

**Comment by zurica2013** [comment]
是字体本身原因吗？可以在哪里自定义替换呢？

**Comment by BigCoke233** [comment]
是字体本身的问题，自定义的话需要改 css 文件，在 `matcha.css` 里找到这一段

```css
.header a,
.small-header a {
	font-family: 'ZCOOL XiaoWei', serif!important;
}
```

应该是在第 97 行，直接删掉就可以，或者你也可以自己改一下字体，改完之后记得清理浏览器缓存。

之后可以考虑增加一个设置项。
